name: Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - "apps/api/**"
      - "apps/worker/**"
      - "apps/bull-board/**"
      - "packages/shared/**"
      - "docker-compose.prod.yml"
      - "scripts/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  ORGANIZATION: fats403

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build -- --filter=@video-venture/shared

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Extract metadata
        id: meta
        run: echo "version=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/videoventure-api:${{ steps.meta.outputs.version }},${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/videoventure-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/worker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/videoventure-worker:${{ steps.meta.outputs.version }},${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/videoventure-worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Bull Board image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/bull-board/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/videoventure-bull-board:${{ steps.meta.outputs.version }},${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/videoventure-bull-board:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "docker-compose.prod.yml,scripts/deploy.sh"
          target: "/opt/videoventure/"
          overwrite: true

      - name: Execute deployment
        uses: appleboy/ssh-action@v1.0.3
        env:
          VERSION: ${{ steps.meta.outputs.version }}
          REGISTRY: ${{ env.REGISTRY }}
          ORGANIZATION: ${{ env.ORGANIZATION }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          envs: VERSION,REGISTRY,ORGANIZATION
          script: |
            cd /opt/videoventure

            # Create the environment variables file
            echo "TAG=$VERSION" > .env.deploy
            echo "DOCKER_REGISTRY=$REGISTRY/$ORGANIZATION" >> .env.deploy

            # Make deployment script executable and run it
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh
